name: Build (iOS)

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: macos-latest
        env:
            XC_VERSION: ${{ '12.2' }}
            XC_WORKSPACE: ${{ 'Skadoosh.xcworkspace' }}
            XC_SCHEME: ${{ 'Skadoosh' }}
        steps:
        - name: Force Xcode "$XC_VERSION" 👊
          run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
        - uses: actions/checkout@v2
        - name: Build App ⚒️
          run: xcodebuild -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
